-- 创建所有需要的数据库
CREATE DATABASE IF NOT EXISTS broker DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS statistics DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS clear DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS gateway_exchange DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

